defaults:
  - main
  - _self_

model_id: deepseek-ai/deepseek-math-7b-instruct
name: deepseek
r: 1
lora_alpha: 2
dataCFG:
  instruction: "There will be an incomplete proof. Please reason step by step to help complete the latex proof and put your final latex sentence within \\boxed{{}}. The statement is: \n"
