
defaults:
  - base
  - dataCFG: main
  - _self_

seed: 1234
test_size: 0.2
r: 2
precision: bfloat16
lora_alpha: 4
modules_limit: 10
batch_size: 1
gradient_accumulation_steps: 1
optim: adamw_torch
warmup_steps: 0.1
max_steps: 250
learning_rate: 4e-4
logging_steps: 1
output: ./results
overwrite: True
