
defaults:
  - base
  - dataCFG: main
  - _self_

seed: 1234
test_size: 0.2
r: 1
lora_alpha: 1
modules_limit: 10
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
optim: adamw_torch
warmup_steps: 0.1
max_steps: 100
learning_rate: 1e-4
logging_steps: 1
output: ./results
overwrite: True
